In [1]:
import torch

# 1. Tensor: Là 1 số, 1 vecto, 1 matrix, hay một array n chiều nào khác

In [2]:
# Number
t1 = torch.tensor(4)
print(t1)
print(t1.dtype)

t2 = torch.tensor(4.)
print(t2)
print(t2.dtype)

tensor(4)
torch.int64
tensor(4.)
torch.float32


In [3]:
# Vecto

t3 = torch.tensor([1,2,3,4,5])
print(t3)
print(t3.dtype)

t4 = torch.tensor([1.,2,3,4,5])
print(t4)
print(t4.dtype)

tensor([1, 2, 3, 4, 5])
torch.int64
tensor([1., 2., 3., 4., 5.])
torch.float32


In [4]:
# Matrix

t5 = torch.tensor([[1.,2,3,4,5]
                    ,[3,4,5,6,7]])
print(t5)
print(t5.dtype)

tensor([[1., 2., 3., 4., 5.],
        [3., 4., 5., 6., 7.]])
torch.float32


In [9]:
# 3-dimentional array

t6 = torch.tensor([
                    [[1.,2,3,4,5]
                    ,[3,4,5,6,7]],
                    [[2,3,4,5,6]
                    ,[5,6,7,8,9]]])
print(t6)
print(t6.dtype)

tensor([[[1., 2., 3., 4., 5.],
         [3., 4., 5., 6., 7.]],

        [[2., 3., 4., 5., 6.],
         [5., 6., 7., 8., 9.]]])
torch.float32


In [10]:
# shape

print(t1.shape)
print(t4.shape)
print(t6.shape)

torch.Size([])
torch.Size([5])
torch.Size([2, 2, 5])


# 2. Gradient

In [11]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [12]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [13]:
# Compute derivatives
y.backward()

In [14]:
# Display gradients
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


# 3. Tensor functions

In [15]:
# Create a tensor with a fixed value for every element
t6 = torch.full((3, 2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [19]:
# Concatenate two tensors with compatible shapes
t7 = torch.cat((t5, t5))
t7

tensor([[1., 2., 3., 4., 5.],
        [3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5.],
        [3., 4., 5., 6., 7.]])

In [20]:
# Compute the sin of each element
t8 = torch.sin(t7)
t8

tensor([[ 0.8415,  0.9093,  0.1411, -0.7568, -0.9589],
        [ 0.1411, -0.7568, -0.9589, -0.2794,  0.6570],
        [ 0.8415,  0.9093,  0.1411, -0.7568, -0.9589],
        [ 0.1411, -0.7568, -0.9589, -0.2794,  0.6570]])

In [23]:
# Change the shape of a tensor
t9 = t8.reshape(10, 2)
t9

tensor([[ 0.8415,  0.9093],
        [ 0.1411, -0.7568],
        [-0.9589,  0.1411],
        [-0.7568, -0.9589],
        [-0.2794,  0.6570],
        [ 0.8415,  0.9093],
        [ 0.1411, -0.7568],
        [-0.9589,  0.1411],
        [-0.7568, -0.9589],
        [-0.2794,  0.6570]])

# 4. Tensor -> numpy and numpy -> tensor

In [24]:
import numpy as np

x = np.array([[1, 2], [3, 4.]])
x

array([[1., 2.],
       [3., 4.]])

In [25]:
# Convert the numpy array to a torch tensor.
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [26]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [27]:
# Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])