# 1. Introduction to Linear Regression

In [1]:
import numpy as np
import torch

In [2]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')

targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

In [3]:
# Convert inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [4]:
# Weights and biases
w = torch.randn(2, 3, requires_grad=True)
b = torch.randn(2, requires_grad=True)
print(w)
print(b)

tensor([[-1.5950, -2.0906, -0.6010],
        [-0.2299, -0.2337,  0.1758]], requires_grad=True)
tensor([ 0.0318, -0.2359], requires_grad=True)


In [5]:
def model(x):
    return x @ w.t() + b

In [6]:
# Generate predictions
preds = model(inputs)
print(preds)

tensor([[-282.3156,  -25.1193],
        [-367.5490,  -30.4744],
        [-453.7318,  -41.3605],
        [-274.7888,  -27.2313],
        [-352.7906,  -26.2321]], grad_fn=<AddBackward0>)


In [7]:
# Compare with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


In [8]:
# MSE loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [9]:
# Compute loss
loss = mse(preds, targets)
print(loss)

tensor(102145.6953, grad_fn=<DivBackward0>)


In [10]:
# Compute gradients
loss.backward()

In [11]:
# Gradients for weights
print(w)
print(w.grad)

tensor([[-1.5950, -2.0906, -0.6010],
        [-0.2299, -0.2337,  0.1758]], requires_grad=True)
tensor([[-35412.9375, -39080.6680, -23871.9355],
        [-10129.9697, -11602.2539,  -7032.0410]])


In [12]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [13]:
# Let's verify that the loss is actually lower
loss = mse(preds, targets)
print(loss)

tensor(102145.6953, grad_fn=<DivBackward0>)


In [14]:
w.grad.zero_()
b.grad.zero_()
print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


In [15]:
# Generate predictions
preds = model(inputs)
print(preds)

# Calculate the loss
loss = mse(preds, targets)
print(loss)

# Compute gradients
loss.backward()
print(w.grad)
print(b.grad)

# Adjust weights & reset gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

print(w)
print(b)

# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor([[-220.0110,   -6.9259],
        [-285.6500,   -6.5444],
        [-356.7046,  -12.9206],
        [-213.0261,   -9.3067],
        [-274.1237,   -3.1806]], grad_fn=<AddBackward0>)
tensor(69021.7344, grad_fn=<DivBackward0>)
tensor([[-28978.8926, -32162.4727, -19603.9141],
        [ -8250.1934,  -9578.3662,  -5784.0078]])
tensor([-346.1031,  -99.7756])
tensor([[-0.9511, -1.3782, -0.1662],
        [-0.0461, -0.0219,  0.3039]], requires_grad=True)
tensor([ 0.0395, -0.2337], requires_grad=True)
tensor(46697.6172, grad_fn=<DivBackward0>)


In [16]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [17]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(166.7779, grad_fn=<DivBackward0>)


In [18]:
# Predictions
preds

tensor([[ 61.6841,  73.7245],
        [ 86.6501, 101.2243],
        [101.3231, 126.2066],
        [ 47.4354,  56.9145],
        [ 94.2813, 108.4438]], grad_fn=<AddBackward0>)

In [19]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

# 2. Linear regression using PyTorch built-ins

In [21]:
import torch.nn as nn

In [20]:
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70], 
                   [74, 66, 43], 
                   [91, 87, 65], 
                   [88, 134, 59], 
                   [101, 44, 37], 
                   [68, 96, 71], 
                   [73, 66, 44], 
                   [92, 87, 64], 
                   [87, 135, 57], 
                   [103, 43, 36], 
                   [68, 97, 70]], 
                  dtype='float32')

targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119],
                    [57, 69], 
                    [80, 102], 
                    [118, 132], 
                    [21, 38], 
                    [104, 118], 
                    [57, 69], 
                    [82, 100], 
                    [118, 134], 
                    [20, 38], 
                    [102, 120]], 
                   dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [22]:
from torch.utils.data import TensorDataset

# Define dataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [23]:
from torch.utils.data import DataLoader

# Define data loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [ 73.,  66.,  44.]])
tensor([[ 22.,  37.],
        [103., 119.],
        [ 82., 100.],
        [118., 134.],
        [ 57.,  69.]])


In [24]:
# Define model
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.2548, -0.5424, -0.0655],
        [-0.4313, -0.0932,  0.4517]], requires_grad=True)
Parameter containing:
tensor([-0.5326, -0.5070], requires_grad=True)


In [25]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[-0.2548, -0.5424, -0.0655],
         [-0.4313, -0.0932,  0.4517]], requires_grad=True),
 Parameter containing:
 tensor([-0.5326, -0.5070], requires_grad=True)]

In [26]:
# Generate predictions
preds = model(inputs)
preds

tensor([[-58.2888, -18.8146],
        [-75.6407, -19.0497],
        [-99.1809, -24.3216],
        [-52.2651, -31.7967],
        [-74.7687,  -7.5957],
        [-58.0011, -19.1527],
        [-75.1638, -18.5048],
        [-99.5012, -24.3013],
        [-52.5528, -31.4586],
        [-74.5794,  -6.7126],
        [-57.8118, -18.2697],
        [-75.3531, -19.3878],
        [-99.6579, -24.8665],
        [-52.4544, -32.6798],
        [-75.0564,  -7.2576]], grad_fn=<AddmmBackward0>)

In [27]:
# Import nn.functional
import torch.nn.functional as F


# Define loss function
loss_fn = F.mse_loss

loss = loss_fn(model(inputs), targets)
print(loss)

tensor(18978.3223, grad_fn=<MseLossBackward0>)


In [28]:
# Define optimizer
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [29]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [30]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 270.4379
Epoch [20/100], Loss: 192.5803
Epoch [30/100], Loss: 51.9742
Epoch [40/100], Loss: 166.7926
Epoch [50/100], Loss: 91.4029
Epoch [60/100], Loss: 54.7896
Epoch [70/100], Loss: 41.5101
Epoch [80/100], Loss: 41.5828
Epoch [90/100], Loss: 14.2043
Epoch [100/100], Loss: 4.1843


In [31]:
# Generate predictions
preds = model(inputs)
preds

tensor([[ 58.2567,  70.9451],
        [ 81.9498, 100.8512],
        [116.5822, 131.4440],
        [ 28.5855,  41.2387],
        [ 97.0577, 116.8945],
        [ 57.2069,  69.9671],
        [ 81.6875, 100.9492],
        [116.8733, 132.0791],
        [ 29.6353,  42.2167],
        [ 97.8452, 117.9705],
        [ 57.9943,  71.0432],
        [ 80.9000,  99.8732],
        [116.8445, 131.3459],
        [ 27.7981,  40.1627],
        [ 98.1075, 117.8724]], grad_fn=<AddmmBackward0>)

In [33]:
# predict
model(torch.tensor([[75, 63, 44.]]))

tensor([[55.0931, 68.3298]], grad_fn=<AddmmBackward0>)